### ISSUE TITLE
驱动源码中貌似没有对按键进行消抖操作，是否能准确识别呢？

### ISSUE THREAD

**Issue by Linjieqiang** [0x1abin/MultiButton#1]

**Comment by 0x1abin** [comment]
你好，消抖的按键驱动最基本的功能了，肯定有的，在：
/*------------button debounce handle---------------*/
	if(read_gpio_level != handle->button_level) { //not equal to prev one
		//continue read 3 times same new level change
		if(++(handle->debounce_cnt) >= DEBOUNCE_TICKS) {
			handle->button_level = read_gpio_level;
			handle->debounce_cnt = 0;
		}
	} else { //leved not change ,counter reset.
		handle->debounce_cnt = 0;
	}

**Comment by Linjieqiang** [comment]
好 看到了 谢谢

**Comment by rockjg0917** [comment]
@0x1abin 您好，支持组合按键吗？
