### ISSUE TITLE
Example里有两个小问题

### ISSUE THREAD

**Issue by lingex** [0x1abin/MultiButton#2]
1.这里注册了个btn2的事件，(上文只有btn1一个按键)
button_attach(&btn2, LONG_PRESS_HOLD,  BTN1_LONG_PRESS_HOLD_Handler);

2.int read_button1_GPIO()
函数返回值与传递值类型不一致导致
button_init(&btn1, read_button1_GPIO, 0);
在MDK下编译会报错，统一为 uint8_t 好一点
uint8_t read_button1_GPIO();

**Comment by 0x1abin** [comment]
已更正，谢谢您的反馈。
