### ISSUE TITLE
多个按键共用同一套长短按阈值参数

### ISSUE THREAD

**Issue by stbanana** [0x1abin/MultiButton#45]
## 多个按键对象共用同一套长短阈值按判断参数，在按键实际功能不同时有很大的问题。
例如我现在的工程，长按power输出，这个长按至少需要1.2秒，但是关闭power输出是短按，同时判断区间来到80ms。(为此在作者的基础上添加了一个短按时间阈值触发事件)
但是像旋钮按键或者其他功能按键则没有这样特化的阈值判断，就可以人性化一些。
## 一个简单的解决方案
在结构体中添加长短按阈值的参数存储，在初始化时绑定即可
# 作者的架构真不错，我要在此基础上把我旋转编码器的驱动也改了
# ：）

**Comment by stbanana** [comment]
@wayneso 作者应该是有自己的考量，这是一个比较优秀的框架，我看了RT-Thread的fork，他们就增加了这个功能。
当然我也fork了一个更符合我个人项目风格的库，而且做了超精简和功能拓展两个版本。可供参考
https://github.com/stbanana/MultiButton

**Comment by wayneso** [comment]
确实，框架简洁而优美，好代码就应该是这个样子，感谢你的分享！ @stbanana
